### ISSUE TITLE
reference to {base} in asset paths

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/svelte-starter#46]
add explanation of how to use {base} in url paths for asset references in css (e.g., background-image: url({path}/assets/...)

**Comment by russellsamora** [comment]
added to readme https://github.com/the-pudding/svelte-starter?tab=readme-ov-file#image-asset-paths

i don't *think* approach that is necessary anymore after some sveltekit changes a few months ago (in action https://the-pudding.github.io/svelte-starter/)
